Update Dockerfile example
Need to fix python version to  python:3.9-alpine as later version has issues with Flasks

current version returns :
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)